version: '3.8'

services:
  # DHT daemon for peer discovery
  dht-daemon:
    build:
      context: .
      dockerfile: Dockerfile.dht
    ports:
      - "${DHT_PORT:-13337}:13337"
    environment:
      - GENESIS_HOST=${GENESIS_HOST:-localhost}
    volumes:
      - ./dht_db:/dht_db
    restart: unless-stopped
    command: ["python3", "dht_daemon.py", "--listen", "0.0.0.0:13337", "--solo"]

  # Geth execution client with AI engine
  geth:
    build:
      context: .
      dockerfile: Dockerfile.geth
    ports:
      - "${GETH_HTTP_PORT:-8545}:8545"
      - "${GETH_P2P_PORT:-30303}:30303"
      - "${GETH_AUTH_PORT:-8551}:8551"
    volumes:
      - ./chain_data:/chain_data
      - ./secrets_data:/secrets
    environment:
      - GENESIS_SEED=${GENESIS_SEED}
      - AI_ENGINE_PORT=${AI_ENGINE_PORT:-8552}
    depends_on:
      - dht-daemon
    restart: unless-stopped

  # Prysm beacon chain with ACK quorum
  prysm-beacon:
    build:
      context: .
      dockerfile: Dockerfile.prysm
    ports:
      - "${PRYSM_GRPC_PORT:-4000}:4000"
      - "${PRYSM_REST_PORT:-3500}:3500"
      - "${PRYSM_P2P_PORT:-13000}:13000"
    volumes:
      - ./chain_data:/chain_data
      - ./secrets_data:/secrets
    environment:
      - GENESIS_SEED=${GENESIS_SEED}
      - AI_QUORUM=${AI_QUORUM:-auto}
    depends_on:
      - geth
    restart: unless-stopped

  # AI trainer with GPU support
  ai-trainer:
    build:
      context: .
      dockerfile: Dockerfile.ai
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - GENESIS_HOST=${GENESIS_HOST:-localhost}
      - DHT_PORT=${DHT_PORT:-13337}
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./model_cache:/model_cache
      - ./data_cache:/data_cache
    depends_on:
      - dht-daemon
    restart: unless-stopped
    command: ["python3", "ai/trainer.py", "--auto-data", "--steps", "1000"]

  # AI averager for loss gate validation with GPU support
  ai-averager:
    build:
      context: .
      dockerfile: Dockerfile.ai
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - GENESIS_HOST=${GENESIS_HOST:-localhost}
      - DHT_PORT=${DHT_PORT:-13337}
      - PRYSM_GRPC_PORT=${PRYSM_GRPC_PORT:-4000}
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./model_cache:/model_cache
    depends_on:
      - dht-daemon
      - prysm-beacon
    restart: unless-stopped
    command: ["python3", "ai/local_averager.py"]

  # AI engine for block validation
  ai-engine:
    build:
      context: .
      dockerfile: Dockerfile.engine
    ports:
      - "${AI_ENGINE_PORT:-8552}:8552"
    environment:
      - DHT_PORT=${DHT_PORT:-13337}
      - GENESIS_HOST=${GENESIS_HOST:-localhost}
    volumes:
      - ./model_cache:/model_cache
    depends_on:
      - dht-daemon
    restart: unless-stopped 