version: '3.8'

services:
  init-secrets:
    image: alpine:latest
    command: >
      sh -c "
        if [ ! -f /secrets/jwt.hex ]; then
          apk add --no-cache openssl &&
          openssl rand -hex 32 > /secrets/jwt.hex &&
          echo 'Generated JWT secret'
        else
          echo 'JWT secret already exists'
        fi
      "
    volumes:
      - secrets_data:/secrets

  dht-daemon:
    build:
      context: .
      dockerfile: Dockerfile.dht
    ports:
      - "${DHT_PORT:-13337}:13337"
    environment:
      - GENESIS_HOST=${GENESIS_HOST:-localhost}
      - GENESIS_SEED=${GENESIS_SEED}
    volumes:
      - dht_db:/dht_db
    networks:
      - pol-network
    restart: unless-stopped
    command: >
      python3 dht_daemon.py 
      --listen 0.0.0.0:13337 
      --solo 
      --persistence-dir /dht_db 
      --log-level INFO

  ai-trainer:
    build:
      context: .
      dockerfile: Dockerfile.ai
    environment:
      - GENESIS_HOST=${GENESIS_HOST:-localhost}
      - GENESIS_SEED=${GENESIS_SEED}
    volumes:
      - model_cache:/model_cache
      - dht_db:/dht_db
    networks:
      - pol-network
    depends_on:
      - dht-daemon
    restart: unless-stopped
    command: >
      python3 ai/trainer.py 
      --steps 1000

  ai-averager:
    build:
      context: .
      dockerfile: Dockerfile.ai
    environment:
      - GENESIS_HOST=${GENESIS_HOST:-localhost}
      - GENESIS_SEED=${GENESIS_SEED}
    volumes:
      - model_cache:/model_cache
      - dht_db:/dht_db
    networks:
      - pol-network
    depends_on:
      - dht-daemon
      - ai-trainer
    restart: unless-stopped
    command: >
      python3 ai/local_averager.py

  ai-engine:
    build:
      context: .
      dockerfile: Dockerfile.engine
    ports:
      - "${AI_ENGINE_PORT:-8552}:8552"
    environment:
      - GENESIS_HOST=${GENESIS_HOST:-localhost}
      - ENGINE_PORT=${AI_ENGINE_PORT:-8552}
      - GETH_RPC_URL=http://geth:8545
    volumes:
      - dht_db:/dht_db
    networks:
      - pol-network
    depends_on:
      - dht-daemon
    restart: unless-stopped

  geth:
    image: ethereum/client-go:v1.13.8
    ports:
      - "${GETH_P2P_PORT:-30303}:30303"
      - "${GETH_HTTP_PORT:-8545}:8545"
      - "${GETH_AUTH_PORT:-8551}:8551"
    volumes:
      - chain_data:/root/.ethereum
      - secrets_data:/secrets
    networks:
      - pol-network
    depends_on:
      - init-secrets
      - ai-engine
    restart: unless-stopped
    command: >
      geth
      --datadir /root/.ethereum
      --networkid 1337
      --port 30303
      --http
      --http.addr 0.0.0.0
      --http.port 8545
      --http.api eth,net,web3,debug,admin,txpool
      --http.corsdomain "*"
      --authrpc.addr 0.0.0.0
      --authrpc.port 8551
      --authrpc.jwtsecret /secrets/jwt.hex
      --allow-insecure-unlock
      --unlock 0x0000000000000000000000000000000000000000
      --password /dev/null
      --mine
      --miner.etherbase 0x0000000000000000000000000000000000000000
      --externalcl http://ai-engine:8552
      --syncmode full
      --gcmode archive
      --verbosity 3

  prysm-beacon:
    build:
      context: .
      dockerfile: Dockerfile.prysm
    ports:
      - "${PRYSM_GRPC_PORT:-4000}:4000"
      - "${PRYSM_REST_PORT:-3500}:3500"
      - "${PRYSM_P2P_PORT:-13000}:13000"
    volumes:
      - chain_data:/data
      - secrets_data:/secrets
      - model_cache:/model_cache
    networks:
      - pol-network
    environment:
      - GENESIS_HOST=${GENESIS_HOST:-localhost}
      - GENESIS_SEED=${GENESIS_SEED}
      - AI_QUORUM=${AI_QUORUM:-auto}
    depends_on:
      - init-secrets
      - geth
      - dht-daemon
    restart: unless-stopped
    command: >
      beacon-chain
      --datadir /data
      --rpc-host 0.0.0.0
      --rpc-port 4000
      --grpc-gateway-host 0.0.0.0
      --grpc-gateway-port 3500
      --p2p-host-ip 0.0.0.0
      --p2p-tcp-port 13000
      --execution-endpoint http://geth:8551
      --jwt-secret /secrets/jwt.hex
      --accept-terms-of-use
      --genesis-state /data/genesis.ssz
      --chain-config-file /data/config.yaml
      --ai-quorum auto
      --verbosity info

networks:
  pol-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  chain_data:
    driver: local
  dht_db:
    driver: local
  model_cache:
    driver: local
  secrets_data:
    driver: local 